# Generated by Django 5.1.15 on 2026-02-14 14:25

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(help_text="Property name, e.g., 'Sunset Apartments'", max_length=200)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True)),
                ('property_type', models.CharField(choices=[('APARTMENT', 'Apartment Building'), ('HOUSE', 'Single Family House'), ('CONDO', 'Condominium'), ('TOWNHOUSE', 'Townhouse'), ('COMMERCIAL', 'Commercial')], default='APARTMENT', max_length=20)),
                ('photo', models.FileField(blank=True, null=True, upload_to='property_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(limit_choices_to={'role': 'LANDLORD'}, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'db_table': 'properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('unit_number', models.CharField(help_text="e.g., 'Apt 4B', 'Unit 101'", max_length=20)),
                ('bedroom_count', models.PositiveSmallIntegerField(default=1)),
                ('bathroom_count', models.DecimalField(decimal_places=1, default=1.0, help_text='Supports half-baths, e.g., 1.5', max_digits=3)),
                ('square_feet', models.PositiveIntegerField(blank=True, null=True)),
                ('rent_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_occupied', models.BooleanField(db_index=True, default=False)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, related_name='units', to='properties.property')),
            ],
            options={
                'db_table': 'units',
                'ordering': ['building', 'unit_number'],
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['owner', 'city'], name='properties_owner_i_4aac96_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['zip_code'], name='properties_zip_cod_924e35_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['is_occupied'], name='units_is_occu_51fc78_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['rent_price'], name='units_rent_pr_d34019_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('building', 'unit_number')},
        ),
    ]
