# Generated by Django 5.1.15 on 2026-02-14 14:25

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date_paid', models.DateTimeField()),
                ('transaction_id', models.CharField(blank=True, help_text='External payment gateway transaction ID.', max_length=100, null=True, unique=True)),
                ('payment_type', models.CharField(choices=[('RENT', 'Rent'), ('LATE_FEE', 'Late Fee'), ('DEPOSIT', 'Security Deposit'), ('REFUND', 'Refund'), ('OTHER', 'Other')], default='RENT', max_length=10)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='leases.lease')),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-date_paid'],
                'indexes': [models.Index(fields=['payment_type', 'payment_status'], name='payments_payment_6c1a9b_idx'), models.Index(fields=['date_paid'], name='payments_date_pa_3419a0_idx')],
            },
        ),
    ]
